package constants

const (
	SERVER_PORT         = "SERVER_PORT"
	ANGLE_ONE_CLIENT_ID = "ANGLE_ONE_CLIENT_ID"
	ANGLE_ONE_PASSWORD  = "ANGLE_ONE_PASSWORD"
	ANGLE_ONE_API_KEY   = "ANGLE_ONE_API_KEY"
	ANGLE_ONE_TOTP_CODE = "ANGLE_ONE_TOTP_CODE"
)
